#!/bin/sh

case $BLOCK_BUTTON in
	1) ~/.config/rofi/scripts/menu_powermenu.sh ;; # opens rofi powermenu
	2) kitty nvim "$0" ;; # opens this file to be edited
    3) kitty sudo powertop
esac


for battery in /sys/class/power_supply/BAT?
do
	capacity=$(cat "$battery"/capacity) || break
	status=$(sed "s/[Dd]ischarging/ /;s/[Nn]ot charging/ /;s/[Cc]harging/ /;s/[Uu]nknown/ /;s/[Ff]ull/ /" "$battery"/status)

	 [ "$capacity" -le 25 ] && [ "$status" = " " ] && status=" "

	printf " %s " "$status"
done
