#!/bin/sh
# ========================================================================= #
#    _________.__                .___                          .__        
#   /   _____/|  |__ _____     __| _/____   _____  __ __  _____|__| ____  
#   \_____  \ |  |  \\__  \   / __ |/  _ \ /     \|  |  \/  ___/  |/ ___\ 
#   /        \|   Y  \/ __ \_/ /_/ (  <_> )  Y Y  \  |  /\___ \|  \  \___ 
#  /_______  /|___|  (____  /\____ |\____/|__|_|  /____//____  >__|\___  >
#          \/      \/     \/      \/            \/           \/        \/ 
# ========================================================================= #
# You can remove music icon in front of song in dwmblocks/config.h
# Set icons here
MUSIC=" "
PAUSE=" "
# Set padding (x:while playing, y:while paused)
x="  "
y=" "

# Gets current song
current=$(mpc current)
# Finds song state
state=$(mpc status | awk '{print $1}' | awk 'NR==2')
# Function to check state of song
getSong()
{
    if [ $state = "[playing]" ]  # If playing
    then 
        printf "    %s%s%s\n" "$MUSIC" "$current" "$x"
    elif [ $state = "[paused]" ]  # If paused
    then
        printf "    %s%s %s%s\n" "$MUSIC" "$current" "$PAUSE" "$y"
    else
        printf "   %sStopped\n" "$MUSIC"
    fi
}
pidof -x mpdup >/dev/null 2>&1 || mpdup &

case $BLOCK_BUTTON in
    # Click: Toggles Play/Pause
	1) mpc toggle | getSong ;;
    # Middle Click: Opens ncmpcpp
	2) mpc status | getSong ; setsid -f "$TERMINAL" ncmpcpp ;;
    # Right Click: Opens up my rofi mpd menu
	3) mpc status | getSong ; ~/.config/rofi/scripts/mpd.sh ;;
    # Shift Scroll Down: Previous Track
	8) mpc prev   | getSong ;;
    # Shift Scroll Up: Next Track
	9) mpc next   | getSong ;;
    # Shift Middle Click: Opens scratchpad for song bar!!!!!!
    7) kitty -T scratchpad3 ncmpcpp;;
    # Shift Click: Open this file
	6) mpc status | getSong ; "$TERMINAL" nvim "$0" ;;
	*) mpc status | getSong ;;
esac
# ========================================================================= #
