#!/bin/sh

volstat=$(pactl list sinks)

echo "$volstat" | grep -q "Mute: yes" && printf " 婢" && exit

vol="$(echo "$volstat" | grep '[0-9]\+%' | sed "s,.* \([0-9]\+\)%.*,\1,;1q")"

if [ "$vol" -gt "70" ]; then
	icon=" 墳"
elif [ "$vol" -lt "30" ]; then
	icon=" 奄"
else
	icon=" 奔"
fi

echo " $icon"
#printf "%s" "$icon" # "$vol"

case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e pulsemixer ;;
	2) pamixer -t ;;
	4) pamixer --allow-boost -i 1 ;;
	5) pamixer --allow-boost -d 1 ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac
